version: "3.4"

services:
  wpgraphql.test:
    image: "wordpress:${WP_VERSION}-php${PHP_VERSION}-apache"
    ports:
      - '80:80'
    environment:
      WORDPRESS_DB_HOST: 'mysql_test'
      WORDPRESS_DB_NAME: 'wpgraphql_test'
      WORDPRESS_DB_USER: 'root'
      WORDPRESS_DB_PASSWORD: 'testing'
    volumes:
      - "${PWD}:/var/www/html/wp-content/plugins/wp-graphql:ro"

  mysql_test:
    image: "${MYSQL_DOCKER_IMAGE}"
    environment:
      MYSQL_DATABASE: 'wpgraphql_test'
      MYSQL_ROOT_PASSWORD: 'testing'
